apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
  - pairs:
      env: prod

patches:
- patch: |-
    - op: replace
      path: /spec/destination/server
      value: https://192.168.254.30:8443
  target:
    kind: Application