apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.11.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true